### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by ZhouCX117** [QianNing0/UDL#2]
Hi, thanks for your excellent work. Where can I download the dataset?

**Comment by ZhouCX117** [comment]
Thanks again! I have found the download site for the dataset. 
Another question: why the variance estimation branch is different from the tail branch for the SQ? How do you design this branch? Looking forward to your reply!

**Comment by guanjingshuo** [comment]
Hi, can I ask the download site for the dataset? Thanks!

**Comment by ZhouCX117** [comment]
@guanjingshuo I download the datasets from https://github.com/jbhuang0604/SelfExSR/tree/master/data.  I run the code on the Set5 dataset and can achieve the results reported in the paper. I don't try on other datasets.

**Comment by guanjingshuo** [comment]
@ZhouCX117 Thanks for your reply!

**Comment by guanjingshuo** [comment]
@ZhouCX117 Hi! I meet some problem, can you help me please? I don't understand why the HR image is required in the LR_bicubic folder here. And if I put the HRs in the folder, there will be another new error.

*FileNotFoundError: No such file: 'E:\E\UDL-main\code\data\benchmark\Set5\LR_bicubic\X4\img_001_SRF_4_HR.png'

**Comment by guanjingshuo** [comment]
![image](https://user-images.githubusercontent.com/63444349/212800546-a60f42fe-768d-4c24-8993-13ddd9e0f93b.png)
![image](https://user-images.githubusercontent.com/63444349/212800572-ec885d5e-d6d3-4d84-affb-0d242f09d430.png)

**Comment by ZhouCX117** [comment]
@guanjingshuo It seems that you should prove the consistency of filenames.
![image](https://user-images.githubusercontent.com/79554332/212806488-00c5248c-0e90-450c-80dc-d9b6aaf0bbd7.png)

**Comment by guanjingshuo** [comment]
@ZhouCX117 Thank you very much！ The problem has already been solved！

**Comment by guanjingshuo** [comment]
@ZhouCX117 Another question I would like to ask is whether you encountered the following problem in the second step of the test?

PermissionError: [Errno 13] Permission denied: '.'

**Comment by guanjingshuo** [comment]
![微信截图_20230117130924](https://user-images.githubusercontent.com/63444349/212814935-c2228ed4-55b1-4db2-9893-30232c162b95.png)
